name: GitHub actions demo
run-name: 🛠️ Testing out GitHub actions

on: 
  push:
    branches:
      - main
      - demo*

env:
  owner_name: jwesterl

jobs:
  basic_workflow:
    if: startsWith(github.ref, 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job basic_workflow is executing as part of new workflow and is owned by $owner_name"
      - run: echo ${{vars.REPO_VAR1}}
      
      # Ensure that .NET is installed
      - name: Install .NET
        uses: codebeltnet/install-dotnet@v1

      - name: Checkout Code
        uses: actions/checkout@v4.1.7

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
        
  win_workflow:
    runs-on: windows-latest
    steps:
      - run: echo "I am on Windows!"
